function navUI(){
	return '  <nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">'
	+'      <div class="container">'
	+'        <a class="navbar-brand js-scroll-trigger" href="#page-top">Start Bootstrap</a>'
	+'        <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">'
	+'          Menu'
	+'          <i class="fa fa-bars"></i>'
	+'        </button>'
	+'        <div class="collapse navbar-collapse" id="navbarResponsive">'
	+'          <ul class="navbar-nav ml-auto">'
	+'         	 <div id="loginDivBtn">'
	+'            <li  class="nav-item mx-0 mx-lg-1" id="login_btn">'
	+'              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#" >Login</a>'
	+'            </li></div>'
	+'         	 <div id="joinDivBtn">'
	+'            <li class="nav-item mx-0 mx-lg-1" id="join_btn">'
	+'              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#">Join</a>'
	+'            </li></div>'
	+'            <li class="nav-item mx-0 mx-lg-1" id="board_write">'
	+'              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#">게시글쓰기</a>'
	+'            <li class="nav-item mx-0 mx-lg-1" id="board_list">'
	+'              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#">게시글목록</a>'
	+'            </li>'
	+'          </ul>'
	+'        </div>'
	+'      </div>'
	+'    </nav>';

}